version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: pnap_postgres
    environment:
      POSTGRES_USER: pnap_admin
      POSTGRES_PASSWORD: Trumanmarcelo_1983
      POSTGRES_DB: pnap_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
